extends:
    - plugin:import/errors
    - plugin:import/warnings
parser: babel-eslint
parserOptions:
    ecmaFeatures:
        jsx: true
env:
  browser: true
  jest: true
plugins:
  - react
settings:
  import/resolver: webpack
rules:
  class-methods-use-this: 0
  no-unused-vars:
    - 2
    - varsIgnorePattern: "_$"
  react/jsx-indent:
    - 2
    - 4
  react/jsx-filename-extension: 0
  react/prefer-stateless-function: 0
  react/prop-types: 0
